matrix:
  include:
    - language: java
      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.gradle'

      before_install:
        - sudo mkdir -p /home/ec2-user/webSrc/MY_INTRODUCE_FILE
        - sudo chmod 777 /home/ec2-user/webSrc/MY_INTRODUCE_FILE
        - cd back-end/
        - chmod +x gradlew

      script: "./gradlew clean build"

    - language: node_js

      node_js:
        - "stable"

      before_install:
        - cd front-end/

      script:
        - npm test
        - npm rum build