matrix:
  include:
    - language: java
      jdk:
        - openjdk8

      cache:
        directories:
          - '$HOME/.m2/repository'
          - '$HOME/.gradle'

      before_install:
        - sudo mkdir -p /home/ec2-user/webSrc/MY_INTRODUCE_FILE
        - sudo chmod 777 /home/ec2-user/webSrc/MY_INTRODUCE_FILE
        - cd back-end/
        - chmod +x gradlew

      script: "./gradlew clean build"

      before_deploy:
        - mkdir -p before-backend-deploy
        - cp scripts/*.sh before-backend-deploy/
        - cp appspec.yml before-backend-deploy/
        - cp build/libs/*.jar before-backend-deploy/
        - cd before-backend-deploy && zip -r before-backend-deploy *
        - cd ../ && mkdir -p deploy-backend
        - mv before-backend-deploy/before-backend-deploy.zip deploy-backend/back-end.zip

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: myintroduce-springboot-build
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: deploy-backend
          wait-until-deployed: true

        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: myintroduce-springboot-build
          key: back-end.zip
          bundle_type: zip
          application: myintroduce-springboot-webservice
          deployment_group: myintroduce-springboot-webservice-group
          region: ap-northeast-2
          wait-until-deployed: true

    - language: node_js
      node_js:
        - "stable"

      before_install:
        - cd front-end/

      script:
        - npm test
        - npm run build

      before_deploy:
        - cp -r build before-frontend-deploy
        - cp scripts/*.sh before-frontend-deploy/
        - cp appspec.yml before-frontend-deploy/
        - cd before-frontend-deploy && zip -r before-frontend-deploy *
        - cd ../ && mkdir -p deploy-frontend
        - mv before-frontend-deploy/before-frontend-deploy.zip deploy-frontend/front-end.zip

      deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: myintroduce-springboot-build
          region: ap-northeast-2
          skip_cleanup: true
          acl: private
          local_dir: deploy-frontend
          wait-until-deployed: true

        - provider: codedeploy
          access_key_id: $AWS_ACCESS_KEY
          secret_access_key: $AWS_SECRET_KEY
          bucket: myintroduce-springboot-build
          key: front-end.zip
          bundle_type: zip
          application: myintroduce-springboot-webservice
          deployment_group: myintroduce-springboot-webservice-group
          region: ap-northeast-2
          wait-until-deployed: true