language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_install:
  - mkdir - p /home/ec2-user/webSrc/MY_INTRODUCE_FILE
  - cd back-end/
  - chmod +x gradlew

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - uok02018496@naver.com